// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ORM2.Models;

namespace ORM2.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210322113336_CreateDatabase")]
    partial class CreateDatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ORM2.Models.Customer", b =>
                {
                    b.Property<int>("customerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("county")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("customer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("state")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("zipcode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("customerID");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("ORM2.Models.Freelancer", b =>
                {
                    b.Property<int>("freelancerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("city")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("county")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("freelancer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("state")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("zipcode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("freelancerID");

                    b.ToTable("freelancers");
                });

            modelBuilder.Entity("ORM2.Models.Price", b =>
                {
                    b.Property<int>("priceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<float>("price")
                        .HasColumnType("real");

                    b.HasKey("priceID");

                    b.ToTable("Prices");
                });

            modelBuilder.Entity("ORM2.Models.Project", b =>
                {
                    b.Property<int>("projectID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("customerID")
                        .HasColumnType("int");

                    b.Property<int>("estimation")
                        .HasColumnType("int");

                    b.HasKey("projectID");

                    b.HasIndex("customerID");

                    b.ToTable("projects");
                });

            modelBuilder.Entity("ORM2.Models.Time", b =>
                {
                    b.Property<int>("LogID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("freelancerID")
                        .HasColumnType("int");

                    b.Property<int>("hours")
                        .HasColumnType("int");

                    b.Property<int?>("priceID")
                        .HasColumnType("int");

                    b.Property<int?>("projectID")
                        .HasColumnType("int");

                    b.Property<DateTime>("workday")
                        .HasColumnType("datetime2");

                    b.HasKey("LogID");

                    b.HasIndex("freelancerID");

                    b.HasIndex("priceID");

                    b.HasIndex("projectID");

                    b.ToTable("times");
                });

            modelBuilder.Entity("ORM2.Models.Project", b =>
                {
                    b.HasOne("ORM2.Models.Customer", "customer")
                        .WithMany()
                        .HasForeignKey("customerID");

                    b.Navigation("customer");
                });

            modelBuilder.Entity("ORM2.Models.Time", b =>
                {
                    b.HasOne("ORM2.Models.Freelancer", "FreelancerID")
                        .WithMany()
                        .HasForeignKey("freelancerID");

                    b.HasOne("ORM2.Models.Price", "price")
                        .WithMany()
                        .HasForeignKey("priceID");

                    b.HasOne("ORM2.Models.Project", "project")
                        .WithMany()
                        .HasForeignKey("projectID");

                    b.Navigation("FreelancerID");

                    b.Navigation("price");

                    b.Navigation("project");
                });
#pragma warning restore 612, 618
        }
    }
}
